Repository joshuajbouw/bevy_tilemap, pull requests merged in 2021-01, with the labels that each got.

#81 Fix hex
  CHANGELOG.md
  examples/Cargo.toml
  examples/assets/textures/hex-boulder.png
  examples/assets/textures/hex-boulder_alt.png
  examples/assets/textures/hex-dwarf.png
  examples/assets/textures/hex-dwarf_alt.png
  examples/assets/textures/hex-floor-dirt.png
  examples/assets/textures/hex-floor-dirt_alt.png
  examples/assets/textures/hex-floor-grass.png
  examples/assets/textures/hex-floor-grass_alt.png
  examples/assets/textures/hex-trees.png
  examples/assets/textures/hex-trees_alt.png
  examples/assets/textures/square-dwarf.png
  examples/assets/textures/square-floor.png
  examples/assets/textures/square-floor_alt.png
  examples/assets/textures/square-wall.png
  examples/examples/hex_tile_even_cols.rs
  examples/examples/hex_tile_even_rows.rs
  examples/examples/hex_tile_odd_cols.rs
  examples/examples/hex_tile_odd_rows.rs
  examples/examples/hex_tile_x.rs
  examples/examples/hex_tile_y.rs
  examples/examples/random_dungeon.rs
  examples/examples/random_world.rs
  examples/examples/square_tile.rs
  examples/examples/stress_dwarves.rs
  src/tilemap.rs
Labels: bug

#83 Fix no_implicit_prelude doc issue
  library/types/src/lib.rs
  src/lib.rs
Labels: bug, documentation

#69 0.3.0 release
  CHANGELOG.md
  Cargo.toml
  README.md
  docs/img/logo.gif
  library/types/CHANGELOG.md
  library/types/Cargo.toml
  library/types/src/lib.rs
  library/types/src/point.rs
  src/lib.rs
  src/prelude.rs
  src/tilemap.rs
Labels: release

#85 Add README.md to examples
  docs/img/hex_tile_even_cols.png
  docs/img/hex_tile_even_rows.png
  docs/img/hex_tile_odd_cols.png
  docs/img/hex_tile_odd_rows.png
  docs/img/hex_tile_x.png
  docs/img/hex_tile_y.png
  docs/img/random_dungeon.png
  docs/img/random_world.png
  docs/img/square_tile.png
  examples/README.md
Labels: documentation

#86 Remove spritesheet ref
  CHANGELOG.md
  docs/img/hex_tile_even_cols.png
  docs/img/hex_tile_even_rows.png
  docs/img/hex_tile_odd_cols.png
  docs/img/hex_tile_odd_rows.png
  docs/img/hex_tile_x.png
  docs/img/hex_tile_y.png
  docs/img/random_dungeon.png
  docs/img/random_world.png
  docs/img/square_tile.png
  examples/README.md
Labels: documentation

#87 Add back in types
  Cargo.toml
Labels: bug

#88 Add logging
  .github/ISSUE_TEMPLATE/bug_report.md
  Cargo.toml
  src/chunk.rs
  src/lib.rs
  src/tilemap.rs
Labels: enhancement

#90 v0.3.1 release
  CHANGELOG.md
  Cargo.toml
  LICENSE
  README.md
  library/types/CHANGELOG.md
  library/types/Cargo.toml
  library/types/src/lib.rs
  src/lib.rs
Labels: release

#93 Fix get_tile_mut
  src/tilemap.rs
Labels: bug

#92 Misc version bumps
  examples/Cargo.toml
  src/lib.rs
Labels: documentation

#91 Add info log to stress dwarves example
  examples/examples/stress_dwarves.rs
Labels: enhancement, examples

#96 Fix auto_configure tile size spam
  src/tilemap.rs
Labels: bug

#94 Auto spawn
  CHANGELOG.md
  Cargo.toml
  docs/release_procedure.md
  examples/examples/random_dungeon.rs
  library/types/src/lib.rs
  src/chunk.rs
  src/lib.rs
  src/tilemap.rs
Labels: enhancement

#97 Add bevy_render features
  Cargo.toml
Labels: enhancement

#100 Drop minor version on crates
  Cargo.toml
Labels: dependencies

#103 Types: Remove minor version from dependencies
  library/types/Cargo.toml
Labels: chore

#104 Rename `tilemap` system to `tilemap_events`
  src/lib.rs
  src/tilemap.rs
Labels: refactor

#105 Re-export tilemap.rs pub to lib.rs
  src/lib.rs
  src/tilemap.rs
Labels: feature

#108 CI macos-11.0 -> macos.10.15 fallback
  .github/workflows/ci.yml
Labels: ci, fix

#102 Expose `ChunkEvents` to public API
  src/tilemap.rs
Labels: feature

#106 Remove auto_configure
  README.md
  src/chunk.rs
  src/lib.rs
  src/tilemap.rs
Labels: api-break

#112 Only apply offset if tilemap chunk dims are even
  src/tilemap.rs
Labels: fix

#113 Stop physics dwarf from sliding around
  examples/examples/physics_dungeon.rs
Labels: fix

#114 Remove collisions if tile is removed
  src/chunk.rs
  src/lib.rs
  src/tile.rs
  src/tilemap.rs
Labels: fix

#115 Redid Tile API
  examples/examples/hex_tile_even_cols.rs
  examples/examples/hex_tile_even_rows.rs
  examples/examples/hex_tile_odd_cols.rs
  examples/examples/hex_tile_odd_rows.rs
  examples/examples/hex_tile_x.rs
  examples/examples/hex_tile_y.rs
  examples/examples/physics_dungeon.rs
  examples/examples/random_dungeon.rs
  examples/examples/random_world.rs
  examples/examples/square_tile.rs
  examples/examples/stress_dwarves.rs
  src/chunk.rs
  src/tile.rs
  src/tilemap.rs
Labels: api-break

#117 Lib wide refactor
  src/chunk.rs
  src/chunk/entity.rs
  src/chunk/layer.rs
  src/chunk/mesh.rs
  src/chunk/mod.rs
  src/chunk/raw_tile.rs
  src/chunk/render/mod.rs
  src/chunk/render/tilemap-hex-x.vert
  src/chunk/render/tilemap-hex-y.vert
  src/chunk/render/tilemap-hexcols-even.vert
  src/chunk/render/tilemap-hexcols-odd.vert
  src/chunk/render/tilemap-hexrows-even.vert
  src/chunk/render/tilemap-hexrows-odd.vert
  src/chunk/render/tilemap-square.vert
  src/chunk/render/tilemap.frag
  src/chunk/system.rs
  src/entity.rs
  src/event.rs
  src/lib.rs
  src/prelude.rs
  src/system.rs
  src/tile.rs
  src/tilemap.rs
Labels: refactor

#118 Collision expansion
  Cargo.toml
  examples/Cargo.toml
  src/chunk/layer.rs
  src/chunk/mod.rs
  src/event.rs
  src/lib.rs
  src/system.rs
  src/tilemap.rs
Labels: feature

#120 Fixed deprecated use of add_layer_with_kind
  examples/examples/random_dungeon.rs
Labels: fix
